ARG GO_VERSION=1.25.0

FROM golang:${GO_VERSION} AS build

ARG MAIN_PACKAGE
ARG BINARY_NAME

WORKDIR /src

COPY . .

RUN test -n "$MAIN_PACKAGE"
RUN test -n "$BINARY_NAME"
RUN test -f go.mod
RUN test -d "${MAIN_PACKAGE#./}"
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o "/out/${BINARY_NAME}" "$MAIN_PACKAGE"

FROM gcr.io/distroless/static-debian12:nonroot

ARG BINARY_NAME

COPY --from=build /out/${BINARY_NAME} /usr/local/bin/server

ENTRYPOINT ["/usr/local/bin/server"]
